name: Tests d'intégration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: npm ci  # ou 'npm install' si tu préfères

      - name: Compiler le TypeScript
        run: npm run build  # ou 'tsc' directement, selon ta config

      - name: Lancer les tests d'intégration
        run: npm run test:integration  # adapte ce script à ce que tu utilises